# Generated by Django 5.0.3 on 2024-11-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
