# Generated by Django 5.0.3 on 2024-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_order_items_remove_order_user_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='Store.cartitem'),
        ),
    ]
