# Generated by Django 5.0.3 on 2024-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_order_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='sent',
            field=models.CharField(default='not sent', max_length=100),
        ),
    ]
