# Generated by Django 5.0.3 on 2024-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_rename_delivery_order_delivered_order_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sent',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(default='packing', max_length=100),
        ),
    ]
