# Generated by Django 5.0.3 on 2024-11-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_productcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolor',
            old_name='size',
            new_name='color',
        ),
    ]
