# Generated by Django 5.0.3 on 2024-11-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_rename_size_productcolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
